### ISSUE TITLE
No response after adding backgroudColor properties on Native Ads

### ISSUE THREAD

**Issue by klyment** [callstack-io/react-native-fbads#23] opened 2016-12-15 16:14 UTC
For any clickable component, if backgroudColor or border property is added, it won't jump to Google Play after clicking it .
For instance
      <View style={styles.ctaButton}>
          <Text style={styles.ctaText}>{nativeAd.callToActionText}</Text>
      </View>
If ctaButton has backgroundColor, it won't response to clicking

**Comment by booboothefool** [comment] 2017-03-17 04:10
@klyment Good catch. I noticed this with some other things too like `zIndex`. Also if you nested a view e.g.

doesn't work
```
      <View style={styles.callToActionView}>
        <Text style={styles.callToActionText}>{nativeAd.callToActionText}</Text>
      </View>
```

works
```
      <Text style={[styles.callToActionView, styles.callToActionText]}>{nativeAd.callToActionText}</Text>
```

**Comment by grabbou** [comment] 2017-08-08 10:51
Can you please provide an example (you can use Expo for that since it has our ads integrated) that demonstrates the issue? 

I am going to close it for now as I wasn't able to reproduce it on latest React Native.

**Closed by grabbou** 2017-08-08 10:51 UTC
